/* Original Klar teaching examples. Vocabulary scope is calibrated against the
 * source references declared in vocabulary.js; Klar is not an official course. */
const GRAMMAR = {
 A1:{title:['礼貌点单与第四格','Polite orders & the accusative'],rule:['möchten 表示礼貌愿望，ich 对应 möchte。直接宾语使用第四格：阳性 ein → einen；阴性 eine 和中性 ein 不变。名词永远大写。','Use möchten for polite wishes; with ich, use möchte. A direct object takes the accusative: masculine ein → einen; feminine eine and neuter ein stay unchanged. Capitalize nouns.'],pattern:'Ich möchte + einen / eine / ein + Nomen, bitte.',examples:[['Ich möchte einen Kaffee, bitte.','我想要一杯咖啡，谢谢。','I would like a coffee, please.'],['Haben Sie eine Speisekarte?','您有菜单吗？','Do you have a menu?'],['Ich möchte ein Wasser.','我想要一杯水。','I would like a water.']],pitfall:['不要说 „Ich möchte ein Kaffee.“：Kaffee 是阳性，作宾语时要用 einen。','Not “Ich möchte ein Kaffee.” Kaffee is masculine, so use einen for the direct object.'],task:['你在咖啡馆。礼貌点一杯茶，再问价格。','At a café, politely order a tea and ask the price.'],answer:'Ich möchte einen Tee, bitte. Was kostet der Tee?'},
 A2:{title:['用情态动词提出请求','Making requests with modal verbs'],rule:['können 表示能力或许可。一般陈述句中，变位的情态动词放第二位，实义动词原形放句末。是非问句中情态动词放第一位。könnten 更委婉。','Können expresses ability or permission. In statements, the conjugated modal is in position two and the infinitive goes last. In yes/no questions, the modal comes first. Könnten is more polite.'],pattern:'Können / Könnten + Sie + … + Infinitiv?',examples:[['Können wir die Wohnung besichtigen?','我们可以看一下这套房子吗？','Can we view the apartment?'],['Ich muss die Miete überweisen.','我必须转账付租金。','I have to transfer the rent.'],['Könnten Sie mir den Vertrag schicken?','您能把合同发给我吗？','Could you send me the contract?']],pitfall:['不要把两个动词都变位。„Ich muss bezahlen.“，不是 „Ich muss bezahle.“。','Do not conjugate both verbs: “Ich muss bezahlen,” not “Ich muss bezahle.”'],task:['写一句话，礼貌询问明天能否看房。','Write a polite question asking whether you can view the apartment tomorrow.'],answer:'Könnten wir die Wohnung morgen besichtigen?'},
 B1:{title:['用 weil 和 dass 组织信息','Organizing ideas with weil & dass'],rule:['weil 引出原因，dass 引出内容。从句中变位动词放句末，并用逗号与主句隔开。从句在前时，后面的主句先放变位动词。','Weil introduces a reason; dass introduces reported content. The conjugated verb goes last in the subordinate clause, separated by a comma. If the subordinate clause comes first, the main clause begins with its conjugated verb.'],pattern:'Hauptsatz, weil / dass + Subjekt + … + Verb.',examples:[['Ich bewerbe mich, weil die Stelle interessant ist.','我申请这份工作，因为这个职位很有意思。','I am applying because the position is interesting.'],['Ich hoffe, dass Sie Zeit haben.','我希望您有时间。','I hope that you have time.'],['Weil ich krank bin, verschiebe ich den Termin.','因为我病了，所以要改期。','Because I am ill, I am rescheduling the appointment.']],pitfall:['„weil ich bin krank“ 词序不对；正确是 „weil ich krank bin“。','Use “weil ich krank bin,” not “weil ich bin krank.”'],task:['给同事写一句话：你今天在家办公，因为身体不舒服。','Tell a colleague you are working from home today because you feel unwell.'],answer:'Ich arbeite heute zu Hause, weil ich mich nicht wohlfühle.'},
 B2:{title:['让步与有层次的论证','Concession & structured arguments'],rule:['obwohl 引导让步从句，变位动词放末尾。trotzdem 是连接副词，在主句中占第一位时，变位动词紧随其后。用 einerseits … andererseits … 呈现两面观点。','Obwohl introduces a concessive subordinate clause with the conjugated verb at the end. Trotzdem is an adverb: when it occupies position one in a main clause, the conjugated verb follows. Use einerseits … andererseits … to contrast perspectives.'],pattern:'Obwohl + … + Verb, Verb + Subjekt + …',examples:[['Obwohl die Miete hoch ist, möchte ich hier wohnen.','虽然租金很高，我还是想住在这里。','Although the rent is high, I want to live here.'],['Die Wohnung ist klein. Trotzdem ist sie praktisch.','这套房很小，但还是很实用。','The apartment is small. Nevertheless, it is practical.'],['Einerseits ist die Lage gut, andererseits ist es laut.','一方面位置好，另一方面比较吵。','On the one hand the location is good; on the other it is noisy.']],pitfall:['obwohl 后用从句词序；trotzdem 后用主句词序。不要混用。','Obwohl requires subordinate-clause order; trotzdem uses main-clause order.'],task:['就城市居住写两句话：先提出优点，再用让步表达缺点。','Write two sentences about city living: mention an advantage and acknowledge a drawback.'],answer:'In der Stadt sind die Wege kurz. Obwohl die Mieten hoch sind, schätze ich die gute Anbindung.'},

};
const UNITS = [
 {id:'a1-cafe',level:'A1',title:['在咖啡馆','At the café'],de:'Im Café',icon:'coffee',video:'jUOvnHOsvXM',videoTitle:'How to order Coffee in Germany?',goal:['学会点单、询价和礼貌表达。','Order drinks, ask prices and speak politely.'],words:[
 ['der Kaffee','咖啡','coffee','die Kaffees · 阳性 / masculine','Ich möchte einen Kaffee, bitte.','我想要一杯咖啡，谢谢。','I would like a coffee, please.','Was kostet der Kaffee?','这杯咖啡多少钱？','How much is the coffee?'],
 ['bestellen','点单；订购','to order','bestellt · hat bestellt','Wir bestellen zwei Kaffee.','我们点两杯咖啡。','We are ordering two coffees.','Möchten Sie etwas bestellen?','您想点些什么吗？','Would you like to order something?'],
 ['die Milch','牛奶','milk','通常无复数 / usually uncountable','Ich trinke meinen Kaffee mit Milch.','我喝咖啡加牛奶。','I drink my coffee with milk.','Haben Sie auch Hafermilch?','你们也有燕麦奶吗？','Do you also have oat milk?'],
 ['bezahlen','付款','to pay','bezahlt · hat bezahlt','Ich möchte bezahlen, bitte.','我想结账，谢谢。','I would like to pay, please.','Kann ich mit Karte bezahlen?','我可以刷卡吗？','Can I pay by card?']]},
 {id:'a1-food',level:'A1',title:['点一份午餐','Ordering lunch'],de:'Im Restaurant',icon:'utensils',video:'jUOvnHOsvXM',videoTitle:'How to order Coffee in Germany?',goal:['从咖啡点单延伸到餐厅用餐。','Extend café ordering skills to restaurant meals.'],words:[
 ['die Speisekarte','菜单','menu','die Speisekarten · 阴性 / feminine','Die Speisekarte, bitte.','请给我菜单。','The menu, please.','Haben Sie eine Speisekarte auf Englisch?','您有英文菜单吗？','Do you have a menu in English?'],
 ['das Wasser','水','water','通常无复数 / usually uncountable','Ein Wasser ohne Kohlensäure, bitte.','请给我一杯不含气的水。','A still water, please.','Ich trinke gern Wasser.','我喜欢喝水。','I like drinking water.'],
 ['die Rechnung','账单','bill','die Rechnungen · 阴性 / feminine','Die Rechnung, bitte.','请结账。','The bill, please.','Ist das die Rechnung für unseren Tisch?','这是我们这桌的账单吗？','Is that the bill for our table?'],
 ['lecker','好吃的','delicious','形容词 / adjective','Die Suppe ist lecker.','这汤很好喝。','The soup is delicious.','Das Essen ist sehr lecker.','饭菜非常好吃。','The food is very delicious.']]},
 {id:'a2-home',level:'A2',title:['寻找新住处','Finding a home'],de:'Eine Wohnung finden',icon:'home',video:'TttobZ9jya8',videoTitle:'Finding an apartment in Germany',goal:['读懂基本房源信息，预约看房。','Understand basic listings and arrange a viewing.'],words:[
 ['die Wohnung','公寓；住房','apartment','die Wohnungen · 阴性 / feminine','Ich suche eine Wohnung mit zwei Zimmern.','我在找一套两室的公寓。','I am looking for a two-room apartment.','Ist die Wohnung noch frei?','这套公寓还空着吗？','Is the apartment still available?'],
 ['die Miete','租金','rent','die Mieten · 阴性 / feminine','Wie hoch ist die Miete?','租金是多少？','How much is the rent?','Die Miete beträgt 800 Euro im Monat.','租金每月 800 欧元。','The rent is 800 euros per month.'],
 ['besichtigen','参观；看房','to view','besichtigt · hat besichtigt','Können wir die Wohnung morgen besichtigen?','我们明天可以看房吗？','Can we view the apartment tomorrow?','Ich möchte das Zimmer besichtigen.','我想看看这个房间。','I would like to view the room.'],
 ['der Termin','预约；约定时间','appointment','die Termine · 阳性 / masculine','Haben Sie am Freitag einen Termin frei?','您周五有空档吗？','Do you have an appointment available on Friday?','Ich muss den Termin verschieben.','我必须改期。','I have to reschedule the appointment.']]},
 {id:'a2-move',level:'A2',title:['搬进新家','Moving in'],de:'Einziehen und ankommen',icon:'key',video:'TttobZ9jya8',videoTitle:'Finding an apartment in Germany',goal:['交流搬家安排和基本租住需求。','Discuss moving arrangements and basic housing needs.'],words:[
 ['der Schlüssel','钥匙','key','die Schlüssel · 阳性 / masculine','Wann kann ich den Schlüssel abholen?','我什么时候可以取钥匙？','When can I collect the key?','Ich habe meinen Schlüssel vergessen.','我忘带钥匙了。','I forgot my key.'],
 ['umziehen','搬家','to move house','zieht um · ist umgezogen','Wir ziehen nächste Woche um.','我们下周搬家。','We are moving next week.','Ich bin nach Berlin umgezogen.','我搬到了柏林。','I moved to Berlin.'],
 ['der Nachbar','邻居（男性）','neighbor (male)','die Nachbarn · 弱变化 / weak noun','Unser Nachbar ist sehr freundlich.','我们的邻居很友好。','Our neighbor is very friendly.','Ich frage den Nachbarn.','我问一下邻居。','I will ask the neighbor.'],
 ['der Vertrag','合同','contract','die Verträge · 阳性 / masculine','Könnten Sie mir den Vertrag schicken?','您能把合同发给我吗？','Could you send me the contract?','Ich möchte den Vertrag zuerst lesen.','我想先读一下合同。','I would like to read the contract first.']]},
 {id:'b1-apply',level:'B1',title:['申请一份工作','Applying for a job'],de:'Die Bewerbung',icon:'briefcase',video:'iyoptTjDtz0',videoTitle:'Jobs and careers',goal:['说明求职动机，写一封简短申请邮件。','Explain your motivation and write a short application email.'],words:[
 ['sich bewerben','申请（工作等）','to apply','bewirbt sich · hat sich beworben','Ich bewerbe mich um die Stelle als Verkäufer.','我申请销售员这个职位。','I am applying for the sales assistant position.','Sie hat sich bei einer Firma beworben.','她向一家公司提交了申请。','She applied to a company.'],
 ['die Erfahrung','经验；经历','experience','die Erfahrungen · 阴性 / feminine','Ich habe Erfahrung im Kundenservice.','我有客服方面的经验。','I have experience in customer service.','Diese Erfahrung war wichtig für mich.','这段经历对我很重要。','That experience was important to me.'],
 ['der Lebenslauf','简历','CV; résumé','die Lebensläufe · 阳性 / masculine','Meinen Lebenslauf finden Sie im Anhang.','附件中是我的简历。','You will find my CV attached.','Ich muss meinen Lebenslauf aktualisieren.','我需要更新简历。','I need to update my CV.'],
 ['zuverlässig','可靠的','reliable','形容词 / adjective','Ich bin pünktlich und zuverlässig.','我守时且可靠。','I am punctual and reliable.','Wir suchen zuverlässige Mitarbeiter.','我们在寻找可靠的员工。','We are looking for reliable employees.']]},
 {id:'b1-work',level:'B1',title:['与同事沟通','Talking with colleagues'],de:'Im Arbeitsalltag',icon:'message',video:'iyoptTjDtz0',videoTitle:'Jobs and careers',goal:['安排工作、改期并解释原因。','Arrange work, reschedule and explain reasons.'],words:[
 ['die Besprechung','会议；讨论','meeting','die Besprechungen · 阴性 / feminine','Die Besprechung beginnt um neun Uhr.','会议九点开始。','The meeting starts at nine.','Ich kann nicht an der Besprechung teilnehmen.','我无法参加会议。','I cannot attend the meeting.'],
 ['verschieben','推迟；改期','to reschedule','verschiebt · hat verschoben','Können wir den Termin auf Montag verschieben?','我们可以把预约改到周一吗？','Can we reschedule the appointment for Monday?','Ich verschiebe die Reise, weil ich krank bin.','因为病了，我推迟了旅行。','I am postponing the trip because I am ill.'],
 ['die Aufgabe','任务','task','die Aufgaben · 阴性 / feminine','Ich habe die Aufgabe schon erledigt.','我已经完成了任务。','I have already completed the task.','Könnten Sie mir die Aufgabe erklären?','您能向我解释一下这个任务吗？','Could you explain the task to me?'],
 ['vereinbaren','约定；商定','to arrange','vereinbart · hat vereinbart','Ich möchte einen Termin vereinbaren.','我想预约一个时间。','I would like to arrange an appointment.','Wir haben einen neuen Termin vereinbart.','我们约好了新的时间。','We arranged a new appointment.']]},
 {id:'b2-city',level:'B2',title:['城市生活的两面','Two sides of city life'],de:'Leben in der Stadt',icon:'building',video:'kf8dPaCLa3k',videoTitle:'Our Tips for Searching for an Apartment in Germany',goal:['比较居住选择，清晰表达利弊。','Compare housing choices and explain advantages and disadvantages.'],words:[
 ['die Lebensqualität','生活质量','quality of life','通常无复数 / usually uncountable','Grünflächen verbessern die Lebensqualität.','绿地能改善生活质量。','Green spaces improve quality of life.','Die Lebensqualität hängt nicht nur vom Einkommen ab.','生活质量不仅仅取决于收入。','Quality of life does not depend only on income.'],
 ['die Anbindung','交通连接','transport connection','die Anbindungen · 阴性 / feminine','Die Wohnung hat eine gute Anbindung an den Nahverkehr.','这套房子公共交通便利。','The apartment has good public transport connections.','Trotz der hohen Miete überzeugt mich die gute Anbindung.','尽管房租高，便利的交通仍然打动了我。','Despite the high rent, the good connections appeal to me.'],
 ['abwägen','权衡','to weigh up','wägt ab · hat abgewogen','Wir müssen die Vor- und Nachteile abwägen.','我们必须权衡利弊。','We need to weigh up the advantages and disadvantages.','Ich habe beide Möglichkeiten sorgfältig abgewogen.','我仔细权衡了两种可能。','I carefully weighed up both options.'],
 ['bezahlbar','负担得起的','affordable','形容词 / adjective','Bezahlbarer Wohnraum ist knapp.','负担得起的住房很紧缺。','Affordable housing is scarce.','Wir brauchen mehr bezahlbare Wohnungen.','我们需要更多可负担的住房。','We need more affordable apartments.']]},
 {id:'b2-debate',level:'B2',title:['表达与回应观点','Expressing and responding to opinions'],de:'Argumente austauschen',icon:'message',video:'kf8dPaCLa3k',videoTitle:'Our Tips for Searching for an Apartment in Germany',goal:['围绕住房话题提出并回应论点。','Present and respond to arguments about housing.'],words:[
 ['der Standpunkt','立场；观点','viewpoint','die Standpunkte · 阳性 / masculine','Ich verstehe Ihren Standpunkt, sehe das aber anders.','我理解您的观点，但我的看法不同。','I understand your viewpoint, but I see it differently.','Könnten Sie Ihren Standpunkt erläutern?','您能阐释一下您的观点吗？','Could you explain your viewpoint?'],
 ['überzeugen','说服','to convince','überzeugt · hat überzeugt','Dieses Argument überzeugt mich nicht.','这个论点无法说服我。','This argument does not convince me.','Die gute Lage hat mich überzeugt.','好的地段说服了我。','The good location convinced me.'],
 ['berücksichtigen','考虑到','to take into account','berücksichtigt · hat berücksichtigt','Man sollte auch die Fahrtkosten berücksichtigen.','还应考虑通勤费用。','One should also consider commuting costs.','Wir haben Ihre Wünsche berücksichtigt.','我们考虑了您的愿望。','We have taken your wishes into account.'],
 ['die Auswirkung','影响；后果','impact','die Auswirkungen · 阴性 / feminine','Hohe Mieten haben Auswirkungen auf den Alltag.','高租金对日常生活有影响。','High rents affect everyday life.','Welche Auswirkungen hat diese Entscheidung?','这个决定有什么影响？','What impact does this decision have?']]},

];
const LEVELS = {A1:['初次见面，德语','Your first German'],A2:['让生活顺畅一点','Make everyday life easier'],B1:['独立表达，自在生活','Express yourself independently'],B2:['说出更完整的想法','Express more complex ideas']};
